# Generated by Django 3.1 on 2021-02-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('website', models.URLField(blank=True)),
                ('address_street', models.CharField(blank=True, max_length=60)),
                ('address_suite', models.CharField(blank=True, max_length=60)),
                ('address_city', models.CharField(blank=True, max_length=60)),
                ('address_zipcode', models.CharField(blank=True, max_length=20)),
                ('address_geo_lat', models.FloatField(blank=True)),
                ('address_geo_lng', models.FloatField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=60)),
                ('company_catchphrase', models.CharField(blank=True, max_length=60)),
                ('company_bs', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=60)),
                ('body', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='postsapp.customuser')),
            ],
        ),
    ]
