# Generated by Django 3.1 on 2020-08-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address_street', models.CharField(max_length=60)),
                ('address_suite', models.CharField(max_length=60)),
                ('address_city', models.CharField(max_length=60)),
                ('address_zipcode', models.CharField(max_length=20)),
                ('address_geo_lat', models.FloatField()),
                ('address_geo_lng', models.FloatField()),
                ('phone', models.CharField(max_length=30)),
                ('website', models.URLField()),
                ('company_name', models.CharField(max_length=60)),
                ('company_catchphrase', models.CharField(max_length=60)),
                ('company_bs', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postsapp.customuser')),
            ],
        ),
    ]
